name: "Build/Test"
on:
  push:
  - master
  pull_request:
  - master
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 2
   - name: Add msbuild to PATH
     uses: microsoft/setup-msbuild@v1.3.1
     env:
       ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
   - name: msbuild
     run: |
       msbuild src\CE.sln /p:platform="x64" /p:configuration="Release"
   - name: test
     run: call Release\Tests_Release_x64.exe

